language: c

compiler:
  - clang
  - gcc

sudo: required

services:
  - docker

env:
  global:
    # DEPLOY_USER
    - secure: "eExkXhN774BWGKtui1zixBgvHMBITDWjMEbDnS30WaZzbRQ35toZ0zXZZQyUyTcEAXG9e3C8puAi/ou78bjNBK/EpN0mJj571tKQCA0NfzC9c+LLBX4DJAgEmXv0SMhOQWP2VAZ3rPKNn+j2NrglxkNqyKwNKHaowuvjorB4AQ40zeAwwpcEPmZE0CAbBQRfnvav/7uxBjK0kiB5qRg26CpC440BfKHzGWxD7H8gH/0+PRLPCzYggH5UyC8GXr5lwGuX+ldT6JkK3L3RvFC39eEnnimsVW5jFthVTLd7Qe3u91GpQ6VYIo4BdhCno3pX+1S53c6SVLB/xahesZdTzWUoiJf78abZF0L5la8AunrzJfJjCMFAPYS7EK7lcNImNAyamyvU9BazO6whhH+fxKj4jFqA87SpWYExrF/NQoY0maoqHafPB8wFxflPPMVfJR0kZY9KBHGOz8Vjj5ojqa82gYMplTmoe8a8wuKNenIXvuuKMN5/MqEc/fxBqVjMN3JfalXCWB4SC4z9x9NXawIUVvgYKuddwdY14XJfdpI2MSATaEUGu9NbDL9CWwDETa6Ip2TJobY5nOTFwmg0XaGO1ZOeatOg2NvPoYTVGYg5NTy85vv7GooVxpvUudRq0WiHv3ta47a+ILelb0PVHoS4KK+QF3OYlzQBKtz1DhU="
    # DEPLOY_HOST
    - secure: "zxthhLsmGdEkTcQVYyzb+EN06CVSg/HtdFP7pBpiUIMEKsL+O0i8UGrnC9Uh+18mY+VHZAMo8OC5vFtIM5Egvlx7hirFmvyHqQfnYlq7G12fEjG7cEvYcBKWUXK8V75EmWodOTts1l+rTULVWZb9tln4Ezo5NS6cLITsaR+iW6E+UI1nb9QHJZRoOWmGtLfsbME+3Qn+xPwAjlAwmb/FJncLyL7CKAPEYXabx7dpucv2G9eVYcgk4KDmJhQehkBtZzeG3pZa12KS0v1ep9kSs+a5Zg7dhrhvu6tkNolmgp0y2KlPyaWd6+HtODcPepc/bpSYMjl4l82ryiZ2W3eT+n5Cmpn70CqjpTJNBkqhqICZFEZDkFMwqaXZag+ufRmo0ftZUphe1TqrItHNlV9/RRpcbmuDruVTo6AT864mb+7XuGAJaTIuF295c4ZoJpw2ouNDo0O6XN9X/7htXzs6dEc6oHXniBW/L2TaBKmo8BozQoVFXSnjHExh+R/KuJ3eHGPiwMe8eiM7DFDzBGoln9W5wIibyZ8P6i1OwzmjO3vU/MAHVs8TNZeWbCxf8LaQ1dzHw7/XQPMfV9CJAD1ZsbFIXQRSHjnhsMz3OZAr8mupzqB0IjFE9gp1M03huJWVZjOYhHiCxvrdBfPklSnukTPdkKKMKoybIhQFAPMDDC8="

arch:
  artifacts:
    - qbs-shared-artifacts.tar.gz
  packages:
    - qbs
    - qt5-tools
    - qt5-declarative
    - libqtxdg
    #- clazy-git
    - xorg-server-xvfb
  script:
    #- export CLAZY_CHECKS="level1"
    - qbs-setup-toolchains --detect
    - qbs-setup-qt /usr/bin/qmake-qt5 qt5
    - qbs config profiles.qt5.baseProfile ${CC}
    - dbus-run-session -- xvfb-run -a -s "-screen 0 800x600x24" qbs build -d build -j $(nproc) --all-products profile:qt5 modules.lirideployment.prefix:/usr

script:
  - "curl -s https://raw.githubusercontent.com/lirios/repotools/develop/travis/docker-travis.sh | bash"

deploy:
  - provider: script
    script: .travis/deploy.sh build/default/libliri-artifacts.tar.gz
    skip_cleanup: true
    on:
      branch: master
      condition: "$CC = gcc -a $TRAVIS_PULL_REQUEST = false"
  - provider: script
    script: .travis/deploy.sh build/default/libliri-artifacts.tar.gz
    skip_cleanup: true
    on:
      branch: develop
      condition: "$CC = gcc -a $TRAVIS_PULL_REQUEST = false"

notifications:
  email: false
  slack: lirios:fdUqVmPzqPskEL1UBhqapZ0w
